### ISSUE TITLE
Add CMake find_package support

### ISSUE THREAD

**Issue by myd7349** [mandreyel/mio#11]
Hi, thanks for this awesome library.
Is there any plan for adding CMake `find_package` support?

**Comment by mandreyel** [comment]
@myd7349 Hey, I'm so glad you like it!

Yes, I've been meaning to extend the current CMake file to support `find_package`, but I'm not yet proficient in CMake (the existing one was contributed by someone else, too...) and since life's been getting in the way lately, I haven't had much time to research it. I'd be more than happy to accept a PR, though! :)

**Comment by mandreyel** [comment]
#13 closes this.
